micronaut:
  application:
    name: dlpflow-downloader
  server:
    port: 10310
    cors:
      enabled: true
      configurations:
        localhost-forwarding:
          allowedOrigins:
            - http://localhost:10310

  security:
    enabled: true
    intercept-url-map:
      - pattern: /**/openapi/**
        httpMethod: GET
        access:
          - isAnonymous()
    token:
      name-key: preferred_username
      jwt:
        signatures:
          jwks:
            keycloak-staging:
              url: 'https://keycloak.staging-bip-app.ssb.no/auth/realms/ssb/protocol/openid-connect/certs'

endpoints:
  prometheus:
    sensitive: false

services:
  secrets:
    impl: GCP


